spring.application.name=onlineShopping
spring.datasource.url=jdbc:postgresql://localhost:5432/medstore
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
hibernate.id.new_generator_mappings=true
hibernate.id.optimizer.pooled.preferred=none

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Jwt essentials
jwt.secret=55c631e7cc254ec418a9680ba6129d6caa2cda4abbfc790fc1644198e6089a8c918e6e7a2ec9aa5f8e9932c77602953b7af446645b44608c6ddf4741801d35ee
jwt.expiration=25200000